### PR TITLE
groups claim parsing

### LINKED ISSUE #323: Issue federation ID tokens with group claim as an array
**What happened?**

- @enj and I were working on https://github.com/vmware-tanzu/pinniped/pull/322.
- We noticed that we issue downstream ID tokens with a `groups` claim formatted either as an array or a string: https://github.com/vmware-tanzu/pinniped/blob/3f08f2e11e5c0599984f16d6b15c5bc2f364ef98/internal/oidc/callback/callback_handler.go#L275-L276.
- We should be consistent about the data type for our downstream `groups` claim.

**What did you expect to happen?**

- We should be consistent about the data type we use for our downstream `groups` claim.
- We should always use an array.

**What is the simplest way to reproduce this behavior?**

**In what environment did you see this bug?**
- Pinniped server version: `v0.3.0`
- Pinniped client version: n/a
- Pinniped container image (if using a public container image): n/a
- Pinniped configuration (what IDP(s) are you using? what downstream credential minting mechanisms are you using?): n/a
- Kubernetes version (use `kubectl version`): n/a
- Kubernetes installer & version (e.g., `kubeadm version`): n/a
- Cloud provider or hardware configuration: n/a
- OS (e.g: `cat /etc/os-release`): n/a
- Kernel (e.g. `uname -a`): n/a
- Others: n/a

**What else is there to know about this bug?**

- We should also try to cast `groupsAsInterface` to an `[]interface{}` in the case that the upstream token has been unmarshaled that way.

### PR DESCRIPTION
**Pull request by margocrawf**
- always return groups as an array in the downstream token
- parse arrays of type interface that contain strings properly
- convert strings to arrays with one string element

Signed-off-by: Margo Crawford <margaretc@vmware.com>

Resolves #323.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: internal/oidc/callback/callback_handler.go [hunk 1]
```diff
@@ -301,9 +325,7 @@ func makeDownstreamSession(subject string, username string, groups interface{})
 	}
 	openIDSession.Claims.Extra = map[string]interface{}{
 		oidc.DownstreamUsernameClaim: username,
-	}
-	if groups != nil {
-		openIDSession.Claims.Extra[oidc.DownstreamGroupsClaim] = groups
+		oidc.DownstreamGroupsClaim:   groups,
```
Comment (enj) [inline internal/oidc/callback/callback_handler.go:328]: Instead of making `getGroupsFromUpstreamIDToken` always return a `[]string{}`, I would do that logic here and just return `nil` in `getGroupsFromUpstreamIDToken`.

File: internal/oidc/callback/callback_handler.go [hunk 2]
```diff
@@ -284,13 +283,38 @@ func getGroupsFromUpstreamIDToken(
...
+		return nil, false
+	}
+
+	groupsAsStrings := make([]string, len(groupsAsInterfaceArray))
+	for i, groupAsInterface := range groupsAsInterfaceArray {
+		groupAsString, okAsString := groupAsInterface.(string)
+		if !okAsString {
+			return nil, false
+		}
+		groupsAsStrings[i] = groupAsString
```
Comment (enj) [inline internal/oidc/callback/callback_handler.go:311]: Filter out empty groups.

**Review by enj — CHANGES_REQUESTED** [review]

**Review by mattmoyer — APPROVED** [review]
